### ISSUE TITLE
java.sql.SQLException: Could not find option with name engine.WarnInterpreterOnly.

### ISSUE THREAD

**Issue by tangyibo** [wise-coders/mongodb-jdbc-driver#16]
Hi,
  when I first use this driver，an error happened like this:
```
java.lang.IllegalArgumentException: Could not find option with name engine.WarnInterpreterOnly.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:130)
	at com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:283)
	at com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:263)
	at com.oracle.truffle.polyglot.OptionValuesImpl.findDescriptor(OptionValuesImpl.java:240)
	at com.oracle.truffle.polyglot.OptionValuesImpl.put(OptionValuesImpl.java:142)
	at com.oracle.truffle.polyglot.OptionValuesImpl.putAll(OptionValuesImpl.java:137)
	at com.oracle.truffle.polyglot.PolyglotImpl.createEngineOptions(PolyglotImpl.java:292)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:234)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:546)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1687)
	at com.wisecoders.dbschema.mongodb.MongoConnection.createContext(MongoConnection.java:413)
	at com.wisecoders.dbschema.mongodb.MongoPreparedStatement.executeQuery(MongoPreparedStatement.java:132)
```

Can you help me? thanks

**Comment by wise-coders** [comment]
Hello,
We released a new version, where we commented out the line where we set the engine.WarnInterpreterOnly.
Could you please test again the driver?
If you tested from DbSchema, you can drop the folder .DbSchema/drivers from the home directory. Next time you will connect the latest driver will be downloaded autoamtically.
Please let me know if this is working fine.
